language: node_js

node_js:
  - 8.6.0

env:
  global:
    - NODE_ENV=test
    - PORT=4040
    - JWT_SECRET=0a6b944d-d2fb-46fc-a85e-0295c986cd9f
    - MONGODB_URI=mongodb://localhost:27017/devfunny-test

services:
  - mongodb

notifications:
  slack: devfunny:n4fDgITtfCGY7sWrqNceOVTR

cache:
  directories:
  - node_modules

git:
  depth: 3

before_install:
  - npm install npm@5 -g
  - npm cache verify
  - npm install -g node-pre-gyp
  - npm prune
  - npm update

install:
  - npm install

script:
  - npm install
  - npm run ci:travis
