language: node_js

node_js:
  - "4.8"
  - "6.10"
  - "7.6"

env:
  - NODE_ENV=development
  - PORT=4040
  - JWT_SECRET=0a6b944d-d2fb-46fc-a85e-0295c986cd9f
  - MONGOOSE_DEBUG=true
  - MONGO_HOST=mongodb://localhost/dev-funny-development
  - MONGO_PORT=27017

services:
  - mongodb

cache:
  directories:
  - node_modules

git:
  depth: 3

script:
  - yarn run test
