version: '2'

services:
  dev-funny-api:
    container_name: dev-funny-api
    build:
      context: .
    volumes:
      - .:/app
      - /app/node_modules/
    ports:
      - "4040:4040"
    env_file:
      - .env
    environment:
      - MONGO_HOST=mongodb://mongo/dev-funny-api-production
    links:
      - mongo
  mongo:
    container_name: dev-funny-mongo
    image: "mongo:3.4.2"
    ports:
      - "27017:27017"
